#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pry'
require 'bundler/setup'

require 'spotify'
require 'spotify/cli'

APP_ROOT = File.expand_path('..', __dir__)
@@configuration = Spotify.configuration
Spotify::CLI.start
